name: NetworkPoints
version: 1.3 (1.7.2+)
description: API for adding points to a player's account using MySQL
author: hatten33

main: net.aerenserve.networkpoints.NetworkPoints

commands:
  mypoints:
    description: Shows how many points you have
    aliases: [points]
