name: NetworkPoints
version: 1.4 (1.7.2+)
description: API for adding points to a player's account using MySQL
author: hatten33

main: net.aerenserve.networkpoints.NetworkPoints

depend: [MineSQLAPI]

commands:
  points:
    description: Base command for using points
